version: '3'
services:
  database:
    container_name: database_message_board
    image: postgres:latest
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: message_board
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
